name: Release

"on":
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to PyPI and GitHub
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bilifm
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup pdm
        id: setup-pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'
      - name: Check output
        run: |
          echo ${{ steps.setup-pdm.outputs.pdm-bin }}
          echo ${{ steps.setup-pdm.outputs.pdm-version }}
          echo ${{ steps.setup-pdm.outputs.python-path }}
          echo ${{ steps.setup-pdm.outputs.python-version }}
      - name: Build package
        run: pdm build
      - name: Publish to PyPI
        run: pdm publish --no-build
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${GITHUB_REF_NAME}" dist/* \
            --repo "${GITHUB_REPOSITORY}" \
            --title "${GITHUB_REF_NAME}" \
            --generate-notes
